---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: another-autoscaler
roleRef:
  kind: ClusterRole
  name: another-autoscaler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: another-autoscaler
  namespace: kube-system
