apiVersion: v1
kind: Service
metadata:
  name: searxng
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: searxng
  sessionAffinity: None
  type: ClusterIP
