---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:develop
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
