apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prowlarr
  updatePolicy:
    updateMode: Auto
    minReplicas: 1
