---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: chevereto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: chevereto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
