apiVersion: v1
kind: Service
metadata:
  name: chevereto
  namespace: chevereto
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: chevereto
  sessionAffinity: None
  type: ClusterIP
