apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lanraragi
  name: lanraragi
  namespace: manga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanraragi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lanraragi
    spec:
      containers:
      - image: difegue/lanraragi:v.0.8.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: web
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: lanraragi
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: web
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/koyomi/lanraragi/database
          name: data
        - mountPath: /home/koyomi/lanraragi/content
          name: content
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lanraragi-db
      - name: content
        persistentVolumeClaim:
          claimName: lanraragi-content
