apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lanraragi
  namespace: manga
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanraragi
  updatePolicy:
    updateMode: Auto
    minReplicas: 1
