---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga
  namespace: kavita
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: kavita
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
