apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kavita
  namespace: kavita
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kavita
  updatePolicy:
    updateMode: Auto
    minReplicas: 1
