---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: signal-cli-rest-api
  name: signal-cli-rest-api
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-cli-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: signal-cli-rest-api
    spec:
      containers:
      - image: bbernhard/signal-cli-rest-api:0.60
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: signal-cli-rest-api
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/.local/share/signal-cli
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
