---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: signal-cli
  name: signal-cli
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-cli
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: signal-cli
    spec:
      containers:
      - image: bbernhard/signal-cli-rest-api
        imagePullPolicy: IfNotPresent
        env:
          - name: MODE
            value: native
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: web
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: signal-cli
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: web
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/.local/share/signal-cli
          name: signal-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: signal-config
        persistentVolumeClaim:
          claimName: signal-config
