---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email-to-signal
  name: email-to-signal
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-to-signal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: email-to-signal
    spec:
      containers:
      - image: leoverto/email2signal:0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: SIGNAL_REST_URL
            value: http://signal-cli-rest-api.signal.svc.cluster.local:8080
          - name: SMTP_HOST
            value: ""
          - name: SMTP_USER
            value: ""
          - name: SMTP_PASSWORD
            value: ""
          - name: SENDER_NUMBER
            valueFrom:
              configMapKeyRef:
                name: signal-sender
                key: SENDER_NUMBER
        livenessProbe:
          failureThreshold: 10
          tcpSocket:
            port: 8025
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: email-to-signal
        ports:
        - containerPort: 8025
          name: mail
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8025
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
