apiVersion: v1
kind: Service
metadata:
  name: signal
  namespace: signal
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: signal-cli
  sessionAffinity: None
  type: ClusterIP
