apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: signal-cli-rest-api
  namespace: signal
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: signal-cli-rest-api
  updatePolicy:
    updateMode: Auto
    minReplicas: 1
